# dnsmasq config for the DHCP server


# disable DHCP for dedicated interfaces
# 
# no-dhcp-interface=

interface=wlan0
#
# with bind-interfaces enabled the start of dnsmasq fails when there is no IP address configured for the interface
# bind-interfaces
#
bind-dynamic

# fixed IP addresses for the DHCP server from dnsmasq
#  
conf-file=/data/local/tmp/sysroot/dnsmasq/etc/dhcp-fix-leases



# *********************************************
# dhcp-range=eth0,192.168.8.40,192.168.8.250,72h

# DHCP is completly disabled if there is no dhcp-range configuration!
# dhcp-range=192.168.1.100,192.168.1.199,72h
#
dhcp-option=option:router,192.168.1.1				# default gateway
dhcp-option=option:ntp-server,192.168.1.1			# ntp timeserver
dhcp-option=23,50						# default ttl
#dhcp-option=121,192.168.99.0/24,192.168.11.99			# static route
dhcp-option=vendor:MSFT,2,1i					# konform für Microsoft Windows
dhcp-option=6,192.168.1.240,192.168.1.1				# DNS SERVER
#???dhcp-option=6,192.168.1.240,192.168.1.242,192.168.1.1
#dhcp-option=69,192.168.10.31					# SMTP SERVER


dhcp-option=66,192.168.1.148

# Set the boot filename for netboot/PXE. You will only need
# this if you want to boot machines over the network and you will need
# a TFTP server; either dnsmasq's built-in TFTP server or an
# external one. (See below for how to enable the TFTP server.)
dhcp-boot=pxelinux.0

# The same as above, but use custom tftp-server instead machine running dnsmasq
#dhcp-boot=pxelinux,server.name,192.168.1.100


