#
# doc: https://wiki.syslinux.org/wiki/index.php?title=Comboot/menu.c32
#
 MENU COLOR TABMSG    37;40 	#80ffffff #00000000
 MENU COLOR HOTSEL    30;47 	#40000000 #20ffffff
 MENU COLOR SEL       30;47 	#40000000 #20ffffff
 MENU COLOR SCROLLBAR 30;47 	#40000000 #20ffffff
 
 MENU WIDTH 80
 MENU MARGIN 10
 MENU PASSWORDMARGIN 3
 MENU ROWS 18
 MENU TABMSGROW 19
 MENU CMDLINEROW 18
 MENU ENDROW -1
 MENU PASSWORDROW 11
 MENU TIMEOUTROW 20
 MENU HELPMSGROW 22
 MENU HELPMSGENDROW -1
# MENU HIDDENROW -2
 MENU HSHIFT 0
 MENU VSHIFT 0

