######################################################################
# WARNING: 'lib/Config_git.pl' is generated by make_patchnum.pl
#          DO NOT EDIT DIRECTLY - edit make_patchnum.pl instead
######################################################################
$Config::Git_Data=<<'ENDOFGIT';
git_commit_id='e634cc838fb1785dfafb5d13b52807ea16b5c52c'
git_describe='v5.44.0'
git_branch='v5.44.0'
git_uncommitted_changes=''
git_commit_id_title='Snapshot of:'
git_commit_date='2026-07-13 17:18:45 +0200'
git_snapshot_date='2026-07-13 17:18:45 +0200'

ENDOFGIT
